name: Build project
on:
  workflow_dispatch: {}
jobs:
  buildForWindows:
    name: Build ${{matrix.projectName}} for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
        unityVersion:
          - 2020.3.26f1
        projectName: 
          - ProjectName
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: ${{ matrix.unityVersion }}
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.projectName }}
          path: build/${{ matrix.projectName }}